from mymmcv.utils import Config
cfg = Config.fromfile('config_a.py')
print(cfg)
cfg = Config.fromfile('config_b.py')
print(cfg)
cfg = Config.fromfile('config_c.py')
print(cfg)
cfg = Config.fromfile('config_d.py')
print(cfg)
cfg = Config.fromfile('config_e.py')
print(cfg)
cfg = Config.fromfile('config_f.py')
print(cfg)
cfg = Config.fromfile('config_g.py')
print(cfg)